#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# PROJECT_NAME := encoder_per_tick
EXTRA_COMPONENT_DIRS += $(IDF_COMPONENTS_PATH)/**
include $(IDF_PATH)/make/project.mk

